# Generated by Django 6.0.2 on 2026-02-08 14:11

import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='общая сумма')),
                ('shipping_address', models.TextField(blank=True, verbose_name='адрес доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к заказу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical заказ',
                'verbose_name_plural': 'historical заказы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='название товара (на момент заказа)')),
                ('product_sku', models.CharField(max_length=50, verbose_name='артикул (на момент заказа)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical товар в заказе',
                'verbose_name_plural': 'historical товары в заказе',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='общая сумма')),
                ('shipping_address', models.TextField(blank=True, verbose_name='адрес доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к заказу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='название товара (на момент заказа)')),
                ('product_sku', models.CharField(max_length=50, verbose_name='артикул (на момент заказа)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'товар в заказе',
                'verbose_name_plural': 'товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название статуса')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_final', models.BooleanField(default=False, verbose_name='финальный статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статусы заказов',
                'ordering': ['created_at'],
            },
        ),
    ]
